### ISSUE TITLE
packaging edge extension fails silently

### ISSUE THREAD

**Issue by cvijanovicn** [manifoldjs/manifoldjs-edgeextension#19]
When trying to create package for Edge extensions, manifoldjs just exits without any error.

I'm running this command:

`manifoldjs -l debug -p edgeextension -f edgeextension package path/to/manifestfolder`

It writes this line:

`[debug] manifoldjs  : Loading platform module: manifoldjs-edgeextension`

after that it just exits to terminal and package is not created.

OS: macOS Mojave 10.14.3
node: 12.5.0
npm: 6.10.0
manifoldjs: 0.7.6

**Comment by am385** [comment]
Hey,
I'm not in a place that I can look at the code right now but here are my quick thoughts. 

Can you confirm if you ran
`manifoldjs -l debug -p edgeextension -f edgeextension -m <EXTENSION LOCATION>\manifest.json`
first.

Then edited the appxmanifest.xml and are trying to run
`manifoldjs -l debug -p edgeextension package <EXTENSION NAME>\edgeextension\manifest\`


Since I can't look through the code right now but it also looks like the -f argument is not needed for the package step. It might cause an issue when passed through as that is telling manifoldjs to look for an edge extensions json manifest and not the appx's appxmanifest.xml.

**Comment by cvijanovicn** [comment]
Hi!

Thanks for answering.

I had run first command before, so I have already directories created. But anyways, I tried to run it again and it finishes with 

`[info ] manifoldjs  : The application(s) are ready.`

but with only root folder created (named same as extensions) and it is empty inside.

for the second line, I tried running it with and without -f argument, and both with same result described in OP.

**Comment by cvijanovicn** [comment]
Any news on this?

One additional info - it appears that problems started with node version update.

**Comment by timbru31** [comment]
I have the same issue with Node.js v10 - `The application(s) are ready.` but nothing is created. With Node.js v8 I get at least some output.
(Besides that packaging for Edge is a pain)

**Comment by am385** [comment]
Hey,
Sorry I couldn't get back to this earlier. I am not on the team that owns this product but I am going to reach out to them to see if someone (@boyofgreen & @jgw96) can help.

**Comment by jgw96** [comment]
Hello all! Quick question, so it sounds like this is working fine on node V8 but not on anything newer, is that correct?

**Comment by cvijanovicn** [comment]
It looks like that is the case. before updating everything was working, I used to create package fairly often (every few days)

If needed I can downgrade node and try.

**Comment by premnirmal** [comment]
Any update on this? I'm seeing the same issue - it fails silently. Only the root directory is created but it is empty with no packaged extension

**Comment by a9udn9u** [comment]
I'm surprised this is not resolved after months, do all Edge extension developers keep a copy of node 8 to package their apps or is there another way to package which doesn't involve manifoldjs? 

**EDIT**
Did some digging, for me the issue happened here:
https://github.com/pwa-builder/pwabuilder-lib/blob/master/lib/platformTools.js#L48
The promise returned by `getPlatformModule()` was rejected, but the error was silently swallowed.
The root cause was
```
ReferenceError: primordials is not defined
    at fs.js:39:5
    at req_ (.../node_modules/natives/index.js:143:24)
    at Object.req [as require] (.../node_modules/natives/index.js:55:10)
    at Object.<anonymous> (.../node_modules/unzip2/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
```
Googled some similar errors related to natives and graceful-fs@3.x, so `npm ls --dev natives`
```
...
└─┬ pwabuilder@2.0.3-rc.1
  └─┬ pwabuilder-edgeextension@2.0.0-rc.2
    └─┬ cloudappx-server@0.0.6
      └─┬ unzip2@0.2.5
        └─┬ fstream@0.1.31
          └─┬ graceful-fs@3.0.12
            └── natives@1.1.6 
```
Used npm-shrinkwrap to override graceful-fs version to 4.1.2, the command started to copy files.

Now I'm getting another error:
```
.../node_modules/q/q.js:155
                throw e;
                ^

TypeError: nodeback is not a function
    at .../node_modules/q/q.js:2055:17
    at runSingle (.../node_modules/q/q.js:137:13)
    at flush (.../node_modules/q/q.js:125:13)
    at processTicksAndRejections (internal/process/task_queues.js:79:11)
```
The `nodeback` parameter is expected to be a function, but in fact a string...
